#
# Copyright (C) 2010 ZHENG Zhong <http://www.zhengzhong.net/>
#
# Created on 2010-02-08.
# $Id$
#

application: vive-le-vendredi
version: 1
runtime: python
api_version: 1


inbound_services:

- mail


handlers:

# Static files.
- url: /static
  static_dir: static

# Favicon.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# Incoming email.
- url: /_ah/mail/.+
  script: handle_incoming_email.py 

# All other incoming requests are handled by the main.py script.
- url: /.*
  script: main.py


# EOF
