#
# Copyright (C) 2010 ZHENG Zhong <http://www.zhengzhong.net/>
#
# Created on 2010-05-12.
# $Id$
#

application: zheng
version: 1
runtime: python
api_version: 1


handlers:

# Static files.
- url: /static
  static_dir: static

# Favicon.
- url: /favicon.ico
  static_files: static/favicon.ico
  upload: static/favicon.ico

# All other incoming requests are handled by the main.py script.
- url: /.*
  script: main.py


# EOF
